### ISSUE TITLE
Remove "Comments" RSS

### ISSUE THREAD

**Issue by wilzbach** [dlang/D-Blog-Theme#1]
![image](https://cloud.githubusercontent.com/assets/4370550/15986344/4d8cd500-3006-11e6-9801-44665039dc72.png)

I think no one of the visitors want to subscribe to the comments - maybe we can rename it too just "RSS" then? :)

**Comment by mdparker** [comment]
Does it hurt to keep it? I have people subscribed to the comments on my personal blogs.

**Comment by wilzbach** [comment]
> Does it hurt to keep it? I have people subscribed to the comments on my personal blogs.

I am a huge fan of simplicity, but of course it doesn't hurt that much ;-)
