### ISSUE TITLE
D syntax highlighting for code snippets

### ISSUE THREAD

**Issue by wilzbach** [dlang/D-Blog-Theme#12]
Afaik highlightjs, and prism support D via plug-ins. 
There is probably no need to load a full-blown editor for code snippets?

**Comment by CyberShadow** [comment]
Um. CodeMirror?

**Comment by mdparker** [comment]
It's not a full-blown editor. It's a plugin with several options, several themes, easy to configure, easy to use in the post editor and, more importantly, has no external dependencies. I use it on one of my other posts and love it. Iv'e got all of the fancy options turned off, but I love the line numbers.

**Comment by wilzbach** [comment]
> It's not a full-blown editor. It's a plugin with several options, several themes, easy to configure, easy to use in the post editor and, more importantly, has no external dependencies.

Are you sure?
Afaict it's uses the ACE editor:

![image](https://cloud.githubusercontent.com/assets/4370550/16198617/d0a0e4a2-3706-11e6-9fce-5274d39bb7df.png)

I don't know anything about WP, but is there an easy way to at least turn syntax highlighting for D on?

**Comment by mdparker** [comment]
Well, that must be what they're using for integration with the admin interface. It's really easy to use there. I didn't realize they were using it for display, too. But it works. Must be why there are no external dependencies. 

The only way to syntax highlight any code is with a plugin.

**Comment by wilzbach** [comment]
> The only way to syntax highlight any code is with a plugin.

That sucks :/
@JackStouffer I have never used WordPress before. Is there a way around loading 340kB of JS on the frontend pages?
It seems a bit wasted if no code (on most pages) or only highlighting is needed. 
Also e.g. Highlight.js which _does_ support D syntax only has 10% of the size.

**Comment by mdparker** [comment]
I don't intend to drop the plugin. I'm quite happy with it, so I'm going to close this. If the file size becomes a problem, then I'll reconsider.
