### ISSUE TITLE
Pretty Permalinks and mod_rewrite

### ISSUE THREAD

**Issue by wilzbach** [dlang/D-Blog-Theme#14]
Can't we enable URL rewrites, s.t. we don't need to have the `index.php` in the URL?
Instead of:

https://dlang.org/blog/index.php/2016/06/16/find-was-too-damn-slow-so-we-fixed-it/

we could have:

https://dlang.org/blog/2016/06/16/find-was-too-damn-slow-so-we-fixed-it

There is a pretty extensive [guide](http://codex.wordpress.org/Using_Permalinks) for Wordpress and they provide copy-paste snippets for Apache2 and Nginx.

**Comment by mdparker** [comment]
I do this with my personal blogs and even now I just don't see the point. Besides, I don't believe mod_rewrite is enabled on the server and I really don't want to bother Jan with it just to get pretty URLs :)

**Comment by wilzbach** [comment]
> I do this with my personal blogs and even now I just don't see the point.

It would hide the ugly fact that we use PHP ;-)

> I don't believe mod_rewrite is enabled

It is ;-)

https://github.com/dlang/dlang.org/blob/master/.htaccess

**Comment by mdparker** [comment]
Yeah, I just did a phpinfo and saw it was loaded.

**Comment by mdparker** [comment]
OK. Since  mod_rewrite is already enabled, I have no problem with it. All set.

**Comment by wilzbach** [comment]
Thanks!
