### ISSUE TITLE
Only post once on Twitter

### ISSUE THREAD

**Issue by wilzbach** [dlang/D-Blog-Theme#15]
It seems like the content is posted _twice_ to Twitter & even once more reposted from Facebook.

![image](https://cloud.githubusercontent.com/assets/4370550/16199575/5a994aac-370a-11e6-91b2-e3a4ca1e8978.png)

**Comment by mdparker** [comment]
OK, that might be a bug in WP related to the way I made the guest post.
I'll keep this open and the next time I publish a guest post from someone
I'll handle it differently and see if the double post disappears.

On Tue, Jun 21, 2016 at 12:14 AM, Sebastian Wilzbach <
notifications@github.com> wrote:

> It seems like the content is posted _twice_ to Twitter & even once more
> reposted from Facebook.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/4370550/16199575/5a994aac-370a-11e6-91b2-e3a4ca1e8978.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/dlang/D-Blog-Theme/issues/15, or mute the thread
> https://github.com/notifications/unsubscribe/AA6EDEwfVORooPQopm-yFHU8CBmbhJ6mks5qNq5sgaJpZM4I5zkv
> .

## 

Mike Parker

**Comment by mdparker** [comment]
Look like the Twitter account is linked to the FB account.

**Comment by wilzbach** [comment]
Yeah just saw that it reposted the dub release  announcement from Facebook. Can we disable this?

**Comment by mdparker** [comment]
What I'll do is disable the automatic posting to Twitter in the blog.

**Comment by wilzbach** [comment]
I am not sure whether this solves the problem as manual   posts like the dub release are still posted twice which looks very unprofessional. I would prefer if we can disable the bridge.

**Comment by mdparker** [comment]
No, they won't be anymore. I posted the DUB announcement to Twitter first, then to FB. That's how I discovered the cause. In future, I'll just post to FB and kill two birds with one stone, though I'll talk to Andrei first. He (or someone) must have set something up recently, because the post on speeding up find was submitted to FB and didn't go to Twitter from there.

**Comment by wilzbach** [comment]
> In future, I'll just post to FB and kill two birds with one stone, though I'll talk to Andrei first. 

Hmm I am not a huge fan of such random links:

![image](https://cloud.githubusercontent.com/assets/4370550/16206342/42ca7fc2-3728-11e6-8153-ebbcc36f6942.png)

(and as you can see the crowd doesn't like them either)

**Comment by mdparker** [comment]
So it's tweering when a post is shared. Definitely not ideal.

**Comment by mdparker** [comment]
OK. I've unlinked the FB page from Twitter. All is right with the world again.
