### ISSUE TITLE
redirect blog.dlang.org

### ISSUE THREAD

**Issue by wilzbach** [dlang/D-Blog-Theme#17]
From the NG: http://forum.dlang.org/post/nkccm3$a5k$1@digitalmars.com

> I just wanted to have a look at the new blog post about ldc, and entered blog.dlang.org without thinking into the browser.
> This does not lead to the official blog anymore, but to the old digitalmars website.

@CyberShadow do you have access to the DNS configs?

**Comment by mdparker** [comment]
Andrei, Jan and I talked about this when we first set up the blog. Andrei was reluctant to add yet another subdoman to dlang.org and we all agreed it was fine not to have it. I don't believe any of us realized it already existed!

**Comment by CyberShadow** [comment]
> Andrei was reluctant to add yet another subdoman to dlang.org

Why??

The way the blog is set up now is extremely specific to the current server configuration. It may be difficult to recreate in the future, and of course if the website and blog were to be hosted on different servers, that would be impossible without proxying the requests one way or another.

**Comment by CyberShadow** [comment]
> @CyberShadow do you have access to the DNS configs?

No.

**Comment by mdparker** [comment]
> Why??

He wasn't against it, just hesitant because it seems a new subdomain is being created for every feature added to the site. Anyway, he's given his thumbs up for the redirect and we're just waiting on a response from Walter. As soon as he says go, I suppose Jan will flip the switch.

**Comment by mdparker** [comment]
Walter gave his approval. Now just waiting for Jan.

**Comment by mdparker** [comment]
Alright. It's finally all squared away.
