### ISSUE TITLE
Issue official press releases 

### ISSUE THREAD

**Issue by wilzbach** [dlang/D-Blog-Theme#18]
After ldc and dub both got their first stable release this month and we now have a beautiful tour for beginners, it's time for making more noise about D. 

In [this](https://forum.dlang.org/thread/lwsnqbravjqbnnryvjkx@forum.dlang.org) thread it was suggested to send press releases from the D Foundation to (major) IT press. I think that's a great idea and we should explore how feasible it is to do this a couple of times a year. Has anyone here already experience with writing collaborating with the IT press? I assume the easiest would to distribute such press releases via the official blog and then send it to the press?

**Comment by mdparker** [comment]
Press releases on a blog? I hope not. That should go on a dedicated news page or something. I know I don't subscribe to blog feeds to read press releases. I think it's a great idea for D Foundation to put them out, but just not on the blog.

**Comment by wilzbach** [comment]
> Press releases on a blog? I hope not. That should go on a dedicated news page or something. I know I don't subscribe to blog feeds to read press releases. 

Fair enough - I thought we make a separate category "press" and hide them from the front page.
How do you imagine "a dedicated news page"? Like the dlang.org [articles](http://dlang.org/articles.html)?

**Comment by mdparker** [comment]
Sorry I never responded to your last question. After giving it some thought, why not publish press releases on the blog? I could give them a dedicated author (e.g. D News Team) in addition to the category. And it would certainly be serving the end of publicizing the language.

That said, there has to be a process in place to create the press releases in the first place. That would be better served by someone with professional PR experience. If this is something you want to pursue, perhaps bring it up in the forums and see what W & A think of it. In the meantime, I intend to post news informally whenever they feed it to me.

So I'll go ahead and close this, as it isn't really a blog "issue" per se. If there's a discussion that makes progress in the forums, I'll join in.

**Comment by wilzbach** [comment]
> That said, there has to be a process in place to create the press releases in the first place. That would be better served by someone with professional PR experience. If this is something you want to pursue, 

Well I am a newbie on this area, but FWIW I made a [thread](http://forum.dlang.org/post/kkfnxxdvryqfgyftxlqx@forum.dlang.org) on the NG, maybe we find someone with experience ;-)

**Comment by mdparker** [comment]
Haha, yeah, I wasn't suggesting you write the press releases! I meant, just getting process started. I'll keep an eye on the thread.
