### ISSUE TITLE
Topnav menu isn't responsive

### ISSUE THREAD

**Issue by wilzbach** [dlang/D-Blog-Theme#2]
Compare

![image](https://cloud.githubusercontent.com/assets/4370550/15986353/7b4d1c52-3006-11e6-88c9-0322416a4f87.png)

with dlang.org:

![image](https://cloud.githubusercontent.com/assets/4370550/15986365/8ad5e65e-3006-11e6-96e1-642fcb253a54.png)

**Comment by mdparker** [comment]
The hamburger menu is back.

**Comment by wilzbach** [comment]
Nice! Thanks for fixing :)
Did you notice that the wordpress menu doesn't have an icon either?

![image](https://cloud.githubusercontent.com/assets/4370550/16214975/1cce2194-375e-11e6-9559-58ea57fec715.png)

**Comment by mdparker** [comment]
Damn. No, I didn't :) I'll open a new issue for that and try to figure it out later.
