### ISSUE TITLE
Short summaries of the blogs instead of full-text

### ISSUE THREAD

**Issue by wilzbach** [dlang/D-Blog-Theme#22]
It's quite hard to have an overview over all the posts that have been published so far.

Also if there are some long posts (https://dlang.org/blog/) takes quite a bit to load everything.
How about doing something like here?
http://dlang.org/articles/

A short - one or two sentences summary allows listing all articles on one page. Or essentially something like this:

https://dlang.org/blog/the-gc-series/

But generated automatically for all categories and listings.

@JackStouffer you have experience with WordPress right?

**Comment by mdparker** [comment]
I can take care of it. I just have to modify the theme. Then I need to make sure each post has a sensible excerpt configured.

**Comment by mdparker** [comment]
Okay. Excerpts are live. They show every where posts are listed -- main page, categories, archives. I've added manual excerpts to the first 20 posts. I'll get the rest over time. The ones I haven't gotten to yet have both "Continue Reading" and "Read More..." links. Not a bug!
