### ISSUE TITLE
Pageload is over 10 seconds

### ISSUE THREAD

**Issue by wilzbach** [dlang/D-Blog-Theme#3]
have a look yourself:

![image](https://cloud.githubusercontent.com/assets/4370550/15986387/06e7eda0-3007-11e6-91cc-c56d9bd34ccc.png)

maybe we can 
- use a CDN for jquery?
- don't ship jquery twice
- don't ship `style.css` twice
- use the already cached `style.css` from dlang.org and just provide a tiny css files with modifications?
  (same goes for the logo and other shared resources)
- do we really need all the other scripts?

**Comment by CyberShadow** [comment]
> use the already cached style.css from dlang.org and just provide a tiny css files with modifications? (same goes for the logo and other shared resources)

Bad idea. dlang.org changes may then break the blog.

**Comment by JackStouffer** [comment]
@mdparker Were you able to get gzip on the server?

**Comment by mdparker** [comment]
@JackStouffer Thanks for the reminder. I've just fired off an email.

**Comment by mdparker** [comment]
@JackStouffer gzip was enabled a couple of days ago. Until I get a cache plugin working, not sure how that's going to hold up with dynamic content. FYI, I got 404 error pages properly configured as well.

@wilzbach How does the load time look now after Jack's changes and with gzip enabled?

**Comment by mdparker** [comment]
@wilzbach Is this good to close now?

**Comment by wilzbach** [comment]
> @wilzbach How does the load time look now after Jack's changes and with gzip enabled?

It's at ~2.5s at my machine now. Great job @JackStouffer  & @mdparker!

> @wilzbach Is this good to close now?

Are you sure gzip is enabled?

![image](https://cloud.githubusercontent.com/assets/4370550/16215216/43a974a6-3760-11e6-9d81-b321f98a636a.png)

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdlang.org%2Fblog%2F

There would still be some stuff to optimize, e.g.
- font-awesome is loaded twice
- ace.js (100kB compressed) is loaded by default
- ...

but I don't want to annoy you with this so much, writing good content is way more important ;-)

**Comment by mdparker** [comment]
> Are you sure gzip is enabled?

Jan assured me it is. I'll look into it.

> font-awesome is loaded twice

This one is beyond me right now, but I'll dig into it at some point if no one else gets there first.

> ace.js (100kB compressed) is loaded by default

I really do not want to give up the convenience of the [syntax highlighter plugin](https://wordpress.org/plugins/mivhak/) I'm using! It integrates directly with the WP post editor so I never have to remember the specific CSS classes (something I always forget with the plugin I'm using on The One with D).

Now that I've got URL rewriting enabled, I'm going to install a cache plugin that uses it. That should help a bit.

**Comment by mdparker** [comment]
OK. Learned something new today. Compression was enabled on the server, but I had to edit the .htaccess to make use of it. I always thought it was automatic. PageSpeed no longer suggests compression, so it appears to be working. I'll look into trimming more fat off as I can, so I'll keep this open a bit longer.

**Comment by mdparker** [comment]
Should be even better now. Got caching enabled and more stuff compressing. I'll try to work on more of PageSpeed's recommendations later.

**Comment by mdparker** [comment]
I'm assuming I can close this now.
