### ISSUE TITLE
Should The Articles on dlang.org Be Moved?

### ISSUE THREAD

**Issue by JackStouffer** [dlang/D-Blog-Theme#6]
Now that we have a blog, https://dlang.org/articles.html seems rather redundant. Should those (or at least some) of those articles be moved to the blog?

Proper attribution could be given, and the publish date could be set in the past as to not crowd out the new stuff.

**Comment by mdparker** [comment]
I don't see the articles as being redundant. I think having a distinction between 'blog posts' and 'articles' is fine. I don't know if it would serve the purpose of the blog to migrate the existing articles over. Or that the blog's existence should preclude adding new articles to that section.

**Comment by wilzbach** [comment]
> Should those (or at least some) of those articles be moved to the blog?

As already said on IRC most of these articles are targeted for "eternity" and should be easily accessible for newbies like e.g. "SafeD" or "C to D".

So in some sense they are _essays_, _reports_, _guides_ or summaries, maybe we should first structure them accordingly on dlang.org and then see whether there's still something that should better be at the blog?

**Comment by mdparker** [comment]
This is another issue that, if anyone feels strongly about it, should probably be brought up in the forums rather than discussed here. If there's general consensus to go forward with it, then I'll do what I can on the blog end to make it happen. Until then, closing.
